apiVersion: v1
kind: Service
metadata:
  name: svc-myapp
  labels:
    app: myapp
spec:
  type: ClusterIP 
  ports:
  - port: 80
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dep-webapplication
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: webapplication
        image: testdot.azurecr.io
        ports:
        - containerPort: 80
